version: '3'
services:

  grafana:
    image: grafana/grafana:6.2.5
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./config/grafana/datasources:/etc/grafana/datasources
      - ./config/grafana/dashboards:/etc/grafana/dashboards
      - ./config/grafana/setup.sh:/setup.sh
    entrypoint: /setup.sh
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
    ports:
      - "3000:3000"
volumes:
  grafana_data: {}
