version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.6.1
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - es_data:/usr/share/elasticsearch/data
    environment:
      - http.port=9200
      - http.cors.allow-origin=*
      - http.cors.enabled=true
      - http.host=0.0.0.0
      - transport.host=0.0.0.0
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms4096m -Xmx4096m"
    ulimits:
      nofile:
        soft: "65536"
        hard: "65536"
      memlock:
        soft: -1
        hard: -1
volumes:
  es_data:
    driver: local