version: "3"
services:
  master_db:
    container_name: master_db
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secured2019
    volumes:
      - ./data/init.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./data/init2.sql:/docker-entrypoint-initdb.d/2-schema.sql
      - master_db_data:/var/lib/postgresql/data

volumes:
  master_db_data:
    driver: local
